name: Ejecutar MEP Scraper

on:
  schedule:
    - cron: '0 12,0 * * *'  # Ejecuta a las 6am 12pm
  workflow_dispatch:  # Permite ejecución manual también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python mep_scraper.py
